server:
  port: 8001
eureka:
 # instance:
#    lease-renewal-interval-in-seconds: 10 #服务的注册涉及到心跳连接，默认为每30s
#    lease-expiration-duration-in-seconds: 30 #服务被移除的时间默认为90s
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
 #   healthcheck:
#      enabled: true #开启心跳
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone:  http://localhost:8001/eureka/
   # registry-fetch-interval-seconds: 30
logging:
  level:
    com.netflix: warn